/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.duda.home.test.api;

import io.swagger.annotations.Api;
import org.springframework.web.bind.annotation.RequestMapping;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-10-28T20:05:33.435Z")

@Api(value = "default", description = "the default API")
public interface DefaultApi {

    @RequestMapping(value = "/")
    String rootGet();

}
