/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.9).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.duda.home.test.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-10-27T21:14:28.877Z")

@Api(value = "enroll", description = "the enroll API")
public interface EnrollApi {

    @ApiOperation(value = "Add a new pet to the store", nickname = "enrollPupilIdPost", notes = "", tags = {})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "OK")})
    @RequestMapping(value = "/enroll/{pupilId}",
            produces = {"application/json"},
            consumes = {"application/json"},
            method = RequestMethod.POST)
    ResponseEntity<Void> enrollPupilIdPost(@ApiParam(value = "ID of pet to return", required = true) @PathVariable("pupilId") Long pupilId);

}
